### ISSUE TITLE
No images in version 1.4.1 and 1.4.0 of the documentation

### ISSUE THREAD

**Issue by sebleblanc** [savonet/savonet.github.io#6]
This page is missing images:

https://www.liquidsoap.info/doc-1.4.1/clocks.html

**Comment by coolaj86** [comment]
# To be more specific

- On <https://www.liquidsoap.info/doc-1.4.2/quick_start.html>
- there is an image titled "A Stream"
- which is supposed to be fetched from <https://www.liquidsoap.info/doc-1.4.2/images/stream.png>
- but is available at <https://www.liquidsoap.info/assets/img/stream.png>

# Incorrect Image URL Paths

It appears that the relative image URLs such as
- `<img src="images/stream.png" alt="A stream">`

need to be replaced with updated URLs such as
- `<img src="/assets/img/stream.png" alt="A stream">` (absolute)
- or `<img src="../assets/img/stream.png" alt="A stream">` (relative)

**Comment by coolaj86** [comment]
@toots Do you have a minute to take a look at this?

**Comment by sebleblanc** [comment]
Alternatively one can add a `<base href>` element in the header.

https://www.w3schools.com/TAGs/tag_base.asp

**Comment by toots** [comment]
This is fixed now, thanks for reporting!!
