### ISSUE TITLE
`reference.html` different between 1.4.0 and 1.4.2

### ISSUE THREAD

**Issue by akosveres** [savonet/savonet.github.io#7]
The references.html is missing previous functionality, like https://www.liquidsoap.info/doc-1.4.0/reference.html and https://www.liquidsoap.info/doc-1.4.2/reference.html are different, 1.4.2 is missing the search form at the top, which was very convenient way of looking up the different language references. 1.4.0 has it.

Was trying to understand where the files come from but couldn't get to a solution, hence I opened an issue, not a PR.

**Comment by smimram** [comment]
Argh. In the meantime, you can still use https://www.liquidsoap.info/doc-dev/reference.html things shouldn't have changed that much.

**Comment by smimram** [comment]
Fixed in fc7ffb46b3f1c9c18d78be2849bff074556ed51e.
