### ISSUE TITLE
[docs] Book link is broken

### ISSUE THREAD

**Issue by vitoyucepi** [savonet/savonet.github.io#8]
**Describe the bug**
The page https://www.liquidsoap.info/doc-2.0.0/book.html contains the book link 

> It can be ordered from Amazon (or read online).

_read online_ links to https://github.com/savonet/book/raw/main/book.pdf
This link doesn't exist anymore.

Also this link has to point to the book for version 2.0.0.

**To Reproduce**
1. Go to https://www.liquidsoap.info/doc-2.0.0/book.html
2. Click _read online_
3. Get github 404

**Expected behavior**
Book pdf link has to be correct.

**Comment by smimram** [comment]
Thanks, this is now corrected.
